// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407095652_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Camera", b =>
                {
                    b.Property<string>("CameraId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("camera_id");

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("coach_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StreamUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stream_url");

                    b.HasKey("CameraId");

                    b.HasIndex("CoachId");

                    b.ToTable("Camera", t =>
                        {
                            t.HasCheckConstraint("chk_camera_status", "status IN ('Active', 'Inactive', 'Faulty')");
                        });
                });

            modelBuilder.Entity("backend.Models.Detection", b =>
                {
                    b.Property<int>("DetectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("detection_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetectionId"));

                    b.Property<string>("CameraId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("camera_id");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.HasKey("DetectionId");

                    b.HasIndex("CameraId");

                    b.ToTable("Detection");
                });

            modelBuilder.Entity("backend.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DetectionId")
                        .HasColumnType("integer")
                        .HasColumnName("detection_id");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<string>("DismissedBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dismissed_by");

                    b.Property<DateTime?>("EnrouteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enroute_at");

                    b.Property<string>("EnrouteBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("enroute_by");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalated_at");

                    b.Property<string>("EscalatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("escalated_by");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verified_by");

                    b.HasKey("IncidentId");

                    b.HasIndex("DetectionId")
                        .IsUnique();

                    b.HasIndex("DismissedBy");

                    b.HasIndex("EnrouteBy");

                    b.HasIndex("EscalatedBy");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("Incident", t =>
                        {
                            t.HasCheckConstraint("chk_incident_has_source", "detection_id IS NOT NULL OR report_id IS NOT NULL");

                            t.HasCheckConstraint("chk_incident_source", "source IN ('AI_DETECTION', 'USER_REPORT')");

                            t.HasCheckConstraint("chk_incident_status", "status IN ('Pending','Verified','En_Route','Escalated','Resolved','Dismissed')");
                        });
                });

            modelBuilder.Entity("backend.Models.LineStation", b =>
                {
                    b.Property<string>("LineId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("line_id");

                    b.Property<string>("StationId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("station_id");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.HasKey("LineId", "StationId");

                    b.HasIndex("StationId");

                    b.ToTable("Line_Station");
                });

            modelBuilder.Entity("backend.Models.Station", b =>
                {
                    b.Property<string>("StationId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("station_id");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("station_name");

                    b.HasKey("StationId");

                    b.ToTable("Station");
                });

            modelBuilder.Entity("backend.Models.TrainAsset", b =>
                {
                    b.Property<string>("TrainId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("train_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("line_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("TrainId");

                    b.HasIndex("LineId");

                    b.ToTable("Train_Asset", t =>
                        {
                            t.HasCheckConstraint("chk_asset_status", "status IN ('Active', 'Inactive', 'Maintenance')");
                        });
                });

            modelBuilder.Entity("backend.Models.TrainCoach", b =>
                {
                    b.Property<string>("CoachId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("coach_id");

                    b.Property<string>("CoachType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("coach_type");

                    b.Property<string>("TrainId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("train_id");

                    b.HasKey("CoachId");

                    b.HasIndex("TrainId");

                    b.ToTable("Train_Coach", t =>
                        {
                            t.HasCheckConstraint("chk_coach_type", "coach_type IN ('Womens_Only', 'Mixed')");
                        });
                });

            modelBuilder.Entity("backend.Models.TrainLine", b =>
                {
                    b.Property<string>("LineId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("line_id");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("line_name");

                    b.HasKey("LineId");

                    b.ToTable("Train_Line");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_id");

                    b.Property<string>("CognitoSub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cognito_sub");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("employee_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable("User", t =>
                        {
                            t.HasCheckConstraint("chk_user_role", "role IN ('Customer', 'Operator', 'Auxiliary')");
                        });
                });

            modelBuilder.Entity("backend.Models.UserReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<string>("CoachId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("coach_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_id");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("violation_type");

                    b.HasKey("ReportId");

                    b.HasIndex("CoachId");

                    b.HasIndex("UserId");

                    b.ToTable("User_Report");
                });

            modelBuilder.Entity("backend.Models.Camera", b =>
                {
                    b.HasOne("backend.Models.TrainCoach", "TrainCoach")
                        .WithMany("Cameras")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainCoach");
                });

            modelBuilder.Entity("backend.Models.Detection", b =>
                {
                    b.HasOne("backend.Models.Camera", "Camera")
                        .WithMany("Detections")
                        .HasForeignKey("CameraId");

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("backend.Models.Incident", b =>
                {
                    b.HasOne("backend.Models.Detection", "Detection")
                        .WithOne("Incident")
                        .HasForeignKey("backend.Models.Incident", "DetectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "DismissedByUser")
                        .WithMany()
                        .HasForeignKey("DismissedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "EnrouteByUser")
                        .WithMany()
                        .HasForeignKey("EnrouteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "EscalatedByUser")
                        .WithMany()
                        .HasForeignKey("EscalatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.UserReport", "UserReport")
                        .WithOne("Incident")
                        .HasForeignKey("backend.Models.Incident", "ReportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Detection");

                    b.Navigation("DismissedByUser");

                    b.Navigation("EnrouteByUser");

                    b.Navigation("EscalatedByUser");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("UserReport");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("backend.Models.LineStation", b =>
                {
                    b.HasOne("backend.Models.TrainLine", "TrainLine")
                        .WithMany("LineStations")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Station", "Station")
                        .WithMany("LineStations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("TrainLine");
                });

            modelBuilder.Entity("backend.Models.TrainAsset", b =>
                {
                    b.HasOne("backend.Models.TrainLine", "TrainLine")
                        .WithMany("TrainAssets")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainLine");
                });

            modelBuilder.Entity("backend.Models.TrainCoach", b =>
                {
                    b.HasOne("backend.Models.TrainAsset", "TrainAsset")
                        .WithMany("TrainCoaches")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainAsset");
                });

            modelBuilder.Entity("backend.Models.UserReport", b =>
                {
                    b.HasOne("backend.Models.TrainCoach", "TrainCoach")
                        .WithMany("UserReports")
                        .HasForeignKey("CoachId");

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("UserReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainCoach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Camera", b =>
                {
                    b.Navigation("Detections");
                });

            modelBuilder.Entity("backend.Models.Detection", b =>
                {
                    b.Navigation("Incident");
                });

            modelBuilder.Entity("backend.Models.Station", b =>
                {
                    b.Navigation("LineStations");
                });

            modelBuilder.Entity("backend.Models.TrainAsset", b =>
                {
                    b.Navigation("TrainCoaches");
                });

            modelBuilder.Entity("backend.Models.TrainCoach", b =>
                {
                    b.Navigation("Cameras");

                    b.Navigation("UserReports");
                });

            modelBuilder.Entity("backend.Models.TrainLine", b =>
                {
                    b.Navigation("LineStations");

                    b.Navigation("TrainAssets");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("UserReports");
                });

            modelBuilder.Entity("backend.Models.UserReport", b =>
                {
                    b.Navigation("Incident");
                });
#pragma warning restore 612, 618
        }
    }
}
