// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "asset_status", new[] { "Active", "Inactive", "Maintenance" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "camera_status", new[] { "Active", "Faulty", "Inactive" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "coach_type", new[] { "Mixed", "Womens_Only" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "incident_source", new[] { "AI_DETECTION", "USER_REPORT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "incident_status", new[] { "Dismissed", "En_Route", "Escalated", "Pending", "Resolved", "Verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sound_alert_mode", new[] { "off", "on", "peak" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "Auxiliary", "Operator", "Passenger" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", new[] { "Active", "Archived", "Suspended" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.AuxiliaryShift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("shift_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShiftId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("shift_date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("ShiftId");

                    b.HasIndex("StationId");

                    b.HasIndex("UserId");

                    b.ToTable("Auxiliary_Shift");
                });

            modelBuilder.Entity("backend.Models.Camera", b =>
                {
                    b.Property<string>("CameraId")
                        .HasColumnType("text")
                        .HasColumnName("camera_id");

                    b.Property<int>("CoachId")
                        .HasColumnType("integer")
                        .HasColumnName("coach_id");

                    b.Property<CameraStatus>("Status")
                        .HasColumnType("camera_status")
                        .HasColumnName("status");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_url");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer")
                        .HasColumnName("train_id");

                    b.HasKey("CameraId");

                    b.HasIndex("TrainId", "CoachId");

                    b.ToTable("Camera");
                });

            modelBuilder.Entity("backend.Models.Detection", b =>
                {
                    b.Property<int>("DetectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("detection_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetectionId"));

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("camera_id");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("line_id");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_id");

                    b.HasKey("DetectionId");

                    b.HasIndex("CameraId");

                    b.HasIndex("LineId", "StationId");

                    b.ToTable("Detection");
                });

            modelBuilder.Entity("backend.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DetectionId")
                        .HasColumnType("integer")
                        .HasColumnName("detection_id");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<string>("DismissedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dismissed_by");

                    b.Property<string>("DismissedComment")
                        .HasColumnType("text")
                        .HasColumnName("dismissed_comment");

                    b.Property<DateTime?>("EnrouteAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("enroute_at");

                    b.Property<string>("EnrouteBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("enroute_by");

                    b.Property<string>("EnrouteComment")
                        .HasColumnType("text")
                        .HasColumnName("enroute_comment");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("escalated_at");

                    b.Property<string>("EscalatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("escalated_by");

                    b.Property<string>("EscalatedComment")
                        .HasColumnType("text")
                        .HasColumnName("escalated_comment");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resolved_by");

                    b.Property<string>("ResolvedComment")
                        .HasColumnType("text")
                        .HasColumnName("resolved_comment");

                    b.Property<IncidentSource>("Source")
                        .HasColumnType("incident_source")
                        .HasColumnName("source");

                    b.Property<IncidentStatus>("Status")
                        .HasColumnType("incident_status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verified_by");

                    b.Property<string>("VerifiedComment")
                        .HasColumnType("text")
                        .HasColumnName("verified_comment");

                    b.HasKey("IncidentId");

                    b.HasIndex("DetectionId")
                        .IsUnique();

                    b.HasIndex("DismissedBy");

                    b.HasIndex("EnrouteBy");

                    b.HasIndex("EscalatedBy");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("Incident", t =>
                        {
                            t.HasCheckConstraint("chk_incident_source", "detection_id IS NOT NULL OR report_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("backend.Models.LineStation", b =>
                {
                    b.Property<string>("LineId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("line_id");

                    b.Property<string>("StationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_id");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.HasKey("LineId", "StationId");

                    b.HasIndex("StationId");

                    b.ToTable("Line_Station");
                });

            modelBuilder.Entity("backend.Models.NotificationPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.Property<SoundAlertMode>("SoundAlerts")
                        .HasColumnType("sound_alert_mode")
                        .HasColumnName("sound_alerts");

                    b.Property<string>("TimeFormat")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("time_format");

                    b.HasKey("UserId");

                    b.ToTable("Notification_Preferences");
                });

            modelBuilder.Entity("backend.Models.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("auth");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256DH")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("p256dh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Push_Subscriptions");
                });

            modelBuilder.Entity("backend.Models.Station", b =>
                {
                    b.Property<string>("StationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("station_name");

                    b.HasKey("StationId");

                    b.ToTable("Station");
                });

            modelBuilder.Entity("backend.Models.TrainAsset", b =>
                {
                    b.Property<int>("TrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("train_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("line_id");

                    b.Property<AssetStatus>("Status")
                        .HasColumnType("asset_status")
                        .HasColumnName("status");

                    b.HasKey("TrainId");

                    b.HasIndex("LineId");

                    b.ToTable("Train_Asset");
                });

            modelBuilder.Entity("backend.Models.TrainCoach", b =>
                {
                    b.Property<int>("TrainId")
                        .HasColumnType("integer")
                        .HasColumnName("train_id");

                    b.Property<int>("CoachId")
                        .HasColumnType("integer")
                        .HasColumnName("coach_id");

                    b.Property<CoachType>("CoachType")
                        .HasColumnType("coach_type")
                        .HasColumnName("coach_type");

                    b.HasKey("TrainId", "CoachId");

                    b.ToTable("Train_Coach");
                });

            modelBuilder.Entity("backend.Models.TrainLine", b =>
                {
                    b.Property<string>("LineId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("line_id");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("line_name");

                    b.HasKey("LineId");

                    b.ToTable("Train_Line");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("MfaEnabled");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("MfaSecret");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<UserStatus>("Status")
                        .HasColumnType("user_status")
                        .HasColumnName("status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.UserReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer")
                        .HasColumnName("coach_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("line_id");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_id");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer")
                        .HasColumnName("train_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("ReportId");

                    b.HasIndex("UserId");

                    b.HasIndex("LineId", "StationId");

                    b.HasIndex("TrainId", "CoachId");

                    b.ToTable("User_Report");
                });

            modelBuilder.Entity("backend.Models.AuxiliaryShift", b =>
                {
                    b.HasOne("backend.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Camera", b =>
                {
                    b.HasOne("backend.Models.TrainCoach", "TrainCoach")
                        .WithMany("Cameras")
                        .HasForeignKey("TrainId", "CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainCoach");
                });

            modelBuilder.Entity("backend.Models.Detection", b =>
                {
                    b.HasOne("backend.Models.Camera", "Camera")
                        .WithMany("Detections")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.LineStation", "LineStation")
                        .WithMany()
                        .HasForeignKey("LineId", "StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("LineStation");
                });

            modelBuilder.Entity("backend.Models.Incident", b =>
                {
                    b.HasOne("backend.Models.Detection", "Detection")
                        .WithOne("Incident")
                        .HasForeignKey("backend.Models.Incident", "DetectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "DismissedByUser")
                        .WithMany()
                        .HasForeignKey("DismissedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "EnrouteByUser")
                        .WithMany()
                        .HasForeignKey("EnrouteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "EscalatedByUser")
                        .WithMany()
                        .HasForeignKey("EscalatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.UserReport", "UserReport")
                        .WithOne("Incident")
                        .HasForeignKey("backend.Models.Incident", "ReportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Detection");

                    b.Navigation("DismissedByUser");

                    b.Navigation("EnrouteByUser");

                    b.Navigation("EscalatedByUser");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("UserReport");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("backend.Models.LineStation", b =>
                {
                    b.HasOne("backend.Models.TrainLine", "TrainLine")
                        .WithMany("LineStations")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Station", "Station")
                        .WithMany("LineStations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("TrainLine");
                });

            modelBuilder.Entity("backend.Models.NotificationPreference", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.PushSubscription", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.TrainAsset", b =>
                {
                    b.HasOne("backend.Models.TrainLine", "TrainLine")
                        .WithMany("TrainAssets")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainLine");
                });

            modelBuilder.Entity("backend.Models.TrainCoach", b =>
                {
                    b.HasOne("backend.Models.TrainAsset", "TrainAsset")
                        .WithMany("TrainCoaches")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainAsset");
                });

            modelBuilder.Entity("backend.Models.UserReport", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("UserReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.LineStation", "LineStation")
                        .WithMany()
                        .HasForeignKey("LineId", "StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.TrainCoach", "TrainCoach")
                        .WithMany("UserReports")
                        .HasForeignKey("TrainId", "CoachId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LineStation");

                    b.Navigation("TrainCoach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Camera", b =>
                {
                    b.Navigation("Detections");
                });

            modelBuilder.Entity("backend.Models.Detection", b =>
                {
                    b.Navigation("Incident");
                });

            modelBuilder.Entity("backend.Models.Station", b =>
                {
                    b.Navigation("LineStations");
                });

            modelBuilder.Entity("backend.Models.TrainAsset", b =>
                {
                    b.Navigation("TrainCoaches");
                });

            modelBuilder.Entity("backend.Models.TrainCoach", b =>
                {
                    b.Navigation("Cameras");

                    b.Navigation("UserReports");
                });

            modelBuilder.Entity("backend.Models.TrainLine", b =>
                {
                    b.Navigation("LineStations");

                    b.Navigation("TrainAssets");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("UserReports");
                });

            modelBuilder.Entity("backend.Models.UserReport", b =>
                {
                    b.Navigation("Incident");
                });
#pragma warning restore 612, 618
        }
    }
}
